[workspace]

members = ["moonpool", "moonpool-core", "moonpool-sim", "moonpool-transport", "moonpool-transport-derive"]
resolver = "2"

[workspace.package]
version = "0.3.0"
repository = "https://github.com/PierreZ/moonpool"
license = "Apache-2.0"
authors = ["Pierre Zemb <contact@pierrezemb.fr>"]
description = "A place to experiment around actors"
documentation = "https://docs.rs/moonpool"
edition = "2024"
